spring:
  datasource:
    core:
      url: jdbc:mysql://10.204.6.5:3306/epd?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: epd
      password: epd_test
      driver-class-name: com.mysql.jdbc.Driver
    epd:
      url: jdbc:mysql://10.204.6.5:3306/epd?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: epd
      password: epd_test
      driver-class-name: com.mysql.jdbc.Driver
    eim:
      url: jdbc:mysql://10.204.6.5:3306/edi_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: edi_platform
      password: edi_platform
      driver-class-name: com.mysql.jdbc.Driver
e2e:
  schedule:
    zkConnect: 10.204.5.14:2181,10.204.16.11:2181,10.204.5.18:2181
    zkUsername: root
    zkPassword: root
    poolSize: 1